### ISSUE TITLE
Spotify doesn't report current_time accurately

### ISSUE THREAD

**Issue by erik** [erik/lastcast#20]
Noticed this locally. When casting spotify, the current time (as reported by PyChromecast) always is ~30 seconds into the track.

This is not a bug in lastcast (likely it's spotify's chromecast integration), but maybe there's a work around.

**Comment by mthssdrbrg** [comment]
I noticed this as well, and have some local changes that manually tracks the current "now playing" track and updates the current time after each poll, it's not very pretty but it seems to work. I haven't dug any deeper into what the actual issue is, but I think it's Spotify's chromecast integration as well.

**Comment by erik** [comment]
I'd actually be really interested in seeing your solution if you don't mind!

**Comment by mthssdrbrg** [comment]
Alright, I'll get it up on Github later today.

**Comment by mthssdrbrg** [comment]
So, here we go https://github.com/mthssdrbrg/lastcast/commit/9086cfc61635c15258911899bc41bfc9810d0d07. It doesn't deal with repeats, ~~but that could be fixed by comparing `started_at` (I _think_ at least, haven't thought it through completely)~~, but I just didn't bother :).

**Comment by erik** [comment]
Awesome! 👍 

Thanks for sharing, I like the idea.

I'll try playing with your implementation when I get some time, see if I can figure out some corner cases.

**Comment by mthssdrbrg** [comment]
Been looking at the code for a bit now and identified a few issues:

* it doesn't handle repeats at all
* it probably doesn't handle seeks (not sure if it's reflected in the status response)

**Comment by erik** [comment]
Thanks again for the patch @mthssdrbrg! Ended up taking the idea and making a couple modifications to handle pausing and controlling the behavior through the config.

I'll leave this issue open for now since the underlying cause isn't fixed, but the most recent version of lastcast should now have much better scrobble behavior for Spotify

**Comment by mthssdrbrg** [comment]
@erik no worries, happy that it was to some use!

**Comment by erik** [comment]
Closing this out for now. Spotify still seems to misreport the timestamp, but the workaround solution has been stable enough in the mean time that it doesn't really matter.
