### ISSUE TITLE
Add libre.fm

### ISSUE THREAD

**Issue by jbmfg** [erik/lastcast#23]
Not sure how similar the apis are for libre.fm and last.fm but would love to see both supported

**Comment by erik** [comment]
Turns out the library I'm using to do the scrobbling (https://github.com/pylast/pylast/) has native support for libre.fm, so this should be pretty easy to add!

I'll look into this when I get some free time.

Thanks for the request!

**Comment by erik** [comment]
Added support for libre.fm in `lastcast==0.3.0`

Let me know if you run into any issues!
