### ISSUE TITLE
Double scobbling

### ISSUE THREAD

**Issue by jbmfg** [erik/lastcast#25]
With the newest version with libre.fm support it is double scrobbling to last.fm.  I am not 100% sure if this occurred before the libre.fm support was added but i dont think it was.  I am also not sure if the double scobble is happening on libre.fm as that site appears to be down right now

**Comment by jbmfg** [comment]
Here is my config & systemd lastcast.service file.  I had to adjust the service file as compared to how you suggest as yours wouldnt work for me.  

jbg@homeserver:~$ cat /home/jbg/.lastcast.toml

[chromecast]
app_whitelist = [ "Google Play Music",]
name = "Kitchen Home"
[librefm]
password = "XXXXXXXXXXXXXX"
user_name = "XXXXXXXXXX"
session_key = "XXXXXXXXXXXXXXXXXX"
[lastfm]
api_key = "XXXXXXXXXXXXXXXXXX"
password = "XXXXXXXXXXXXX"
user_name = "XXXXXXXX"
api_secret = "XXXXXXXXXXXXXXXXXXXXX"

jbg@homeserver:~$ cat /etc/systemd/system/lastcast.service

[Unit]
Description=lastcast
Requires=multi-user.target

[Service]
Type=simple
User=jbg
ExecStart=/home/jbg/.local/bin/lastcast --config /home/jbg/.lastcast.toml
Restart=on-failure
RestartSec=5
KillMode=process

[Install]
WantedBy=multi-user.target

**Comment by jbmfg** [comment]
Did some testing and I think this is related to libre.fm being down.  I watched the service closely while playing a song and saw that it crashed.  It restarted and that's when i could see a double scrobble on last.fm.  When i removed libre.fm settings from my config file i didnt see the double scrobble occurring since the service didnt crash.  Perhaps just handling scrobbling errors differently may help this?

**Comment by erik** [comment]
Makes sense, thanks for the report. 

I'll add more error handling around calling lastfm and librefm. Do you have a stack trace from when you saw the crash and double scrobble?

**Comment by erik** [comment]
Also:

> I had to adjust the service file as compared to how you suggest as yours wouldnt work for me.

What wasn't working? I can update the docs to be more general, I only tested on ubuntu and debian

**Comment by jbmfg** [comment]
I dont have a stacktrace, sorry.  I'm also not sure what wasn't working in the systemd service, it just kept crashing on start.  I can go back see if i can figure it out.  Im on Ubuntu 17.04 btw

**Comment by erik** [comment]
Hi @jbmfg, thanks again for the report. 

The fixed version is now available at `lastcast==0.3.1`

`pip install --upgrade lastcast`

Let me know if you run into any issues!
