### ISSUE TITLE
Often Misses Scrobbles

### ISSUE THREAD

**Issue by corvar** [erik/lastcast#27]
I have been using lastcast for about a week, and can't say I have done any significant troubleshooting, but it seems like scrobbles are pretty regularly missed.  I see the song get updated on last.fm as "Scrobbling now" but it never actually gets scrobbled.  The next track starts, Scrobbling now gets updated, but the previous track never actually scrobbles.

**Comment by erik** [comment]
Thank you for reporting!

Are you scrobbling Spotify by any chance? There is a known upstream issue (https://github.com/erik/lastcast/issues/20) that prevents Spotify from working properly. Unfortunately there only seem to be hack fixes around the issue at the moment.

**Comment by corvar** [comment]
Apologies for the sub-par issue report, after I hit submit I realized I gave no details, versions, etc.

This does seem like it's the possible issue, and I grabbed the possible fix and will give it a try and report back.  I had looked at that issue, but it wasn't obvious from it that it was causing lastcast to miss scrobbles.

**Comment by erik** [comment]
No problem! I do appreciate the issue, since it does seem like this is affecting a bunch of other people as well. I'm going to try hacking on @mthssdrbrg's patch soon and see if I can get a fix merged in.

**Comment by corvar** [comment]
With @mthssdrbrg 's patch, I went from getting about 30% success in scrobbling to ~100%.  In that every track I have played since I applied it has scrobbled.

**Comment by erik** [comment]
Glad it worked for you @corvar!

I pushed a new version of lastcast that should support this behavior out of the box.

`lastcast==0.4.0`
