### ISSUE TITLE
Rebooting router causes lastcast to fail

### ISSUE THREAD

**Issue by thecivvie** [erik/lastcast#31]
If I reboot my router, lastcast  fails with a no route to host. It doesn't crash just seems to hang. A systemd restart fixes it but scrobbles are lost

**Comment by erik** [comment]
Thanks for reporting!

Would you be able to provide a stacktrace to make this easier to debug?

**Comment by thecivvie** [comment]
Does this help:

* lastcast.service - Lastcast Server
   Loaded: loaded (/etc/systemd/system/lastcast.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2017-11-27 13:29:28 UTC; 8h ago
 Main PID: 1411 (lastcast)
   CGroup: /system.slice/lastcast.service
           `-1411 /usr/bin/python3 /usr/local/bin/lastcast

Nov 27 22:15:24 pi3 lastcast[1411]: Traceback (most recent call last):
Nov 27 22:15:24 pi3 lastcast[1411]:   File "/usr/local/lib/python3.5/dist-packages/pychromecast/socket_client.py", line 246, in initialize_connection
Nov 27 22:15:24 pi3 lastcast[1411]:     self.socket.connect((self.host, self.port))
Nov 27 22:15:24 pi3 lastcast[1411]:   File "/usr/lib/python3.5/ssl.py", line 1027, in connect
Nov 27 22:15:24 pi3 lastcast[1411]:     self._real_connect(addr, False)
Nov 27 22:15:24 pi3 lastcast[1411]:   File "/usr/lib/python3.5/ssl.py", line 1014, in _real_connect
Nov 27 22:15:24 pi3 lastcast[1411]:     socket.connect(self, addr)
Nov 27 22:15:24 pi3 lastcast[1411]: OSError: [Errno 113] No route to host
Nov 27 22:15:48 pi3 lastcast[1411]: Reconnecting to cast device...
Nov 27 22:15:58 pi3 lastcast[1411]: Using chromecast: Living Room speaker

Sean

**Comment by thecivvie** [comment]
Just as a note, it seems to be scrobbling after this reboot. I am not sure what the error was the last time, but the traceback was exactly the same

**Comment by erik** [comment]
It does help, thank you!

Weird that the stack trace starts in the pychromecast library, might make it harder to catch this in lastcast. I'll try to dig into the library code to see if there's potentially an issue upstream.

Are there any specific steps to reproduce this? Is it basically just pull the ethernet plug while lastcast is running?

Also, the process id doesn't seem to change, so it looks like lastcast recovers 24 minutes later within the same process, which is a little surprising. Really odd that it takes that long.

Thanks again for the help!

**Comment by erik** [comment]
Very preliminary digging suggests that pychromecast needs to be modified on this line to also catch exceptions of type `os.error`:

https://github.com/balloob/pychromecast/blob/master/pychromecast/socket_client.py?utf8=%E2%9C%93#L258

Python 3 docs seem to support this theory:

> starting from Python 3.3, errors related to socket or address semantics raise OSError or one of its subclasses (they used to raise socket.error).

**Comment by thecivvie** [comment]
Not sure, I came down this morning and played several tracks on the GH before I realised that it wasn't scobbling. Well in fact it was when I noticed my smart plug was not responding either. Sadly being where I am, I am on a mobile broadband, not wired

**Comment by erik** [comment]
Hmm... could you actually let me know which version of Python you're using?

Issue might not be what I initially suspected.

**Comment by thecivvie** [comment]
Python 2.7.13

Unless it was the GH it could not connect to.

**Comment by erik** [comment]
Thanks!

I submitted a patch upstream. When that lands, I'll update the pychromecast version dependency and release a new version of lastcast, hopefully that will fix this issue for you.

If you want to hack around it for now, you could try manually modifying `/usr/local/lib/python3.5/dist-packages/pychromecast/socket_client.py` with this change: https://github.com/erik/pychromecast/commit/0b0e89bd06147517e9b05b6b819ad4c2e373e304

**Comment by erik** [comment]
Wait... I just realized: 

> /usr/local/lib/python3.5

Now I'm confused.

**Comment by thecivvie** [comment]
To be honest, I am not sure what is going on. it was installed on the Pi automatically

**Comment by erik** [comment]
Could you try manually applying the patch I linked above?  I'm a little lost as well, but my best guess is that it will fix your issue.

**Comment by erik** [comment]
Hi @thecivvie, I recently upgraded the pychromecast version that lastcast uses, which should include the fix.

When you get a chance, please try out the most recent release to see if the issue is resolved for you!

`pip install --upgrade lastcast`

**Comment by thecivvie** [comment]
Sorry, been chaos here for the last few weeks.

issue still continues. i have to restart lastcast every day now. Seems to stall on a client serve connection error. i will log onto Pi and get the errors:

Jan 07 14:42:00 pi3 lastcast[6711]: WARNING:pychromecast.socket_client:Heartbeat timeout, resetting connection
Jan 07 21:21:15 pi3 lastcast[6711]: WARNING:pychromecast.socket_client:Heartbeat timeout, resetting connection
Jan 07 21:21:20 pi3 lastcast[6711]: WARNING:pychromecast.socket_client:Heartbeat timeout, resetting connection
Jan 07 21:21:20 pi3 lastcast[6711]: WARNING:pychromecast.socket_client:Heartbeat timeout, resetting connection
Jan 07 21:59:07 pi3 lastcast[6711]: WARNING:pychromecast.socket_client:Heartbeat timeout, resetting connection
Jan 07 21:59:07 pi3 lastcast[6711]: WARNING:pychromecast.socket_client:Heartbeat timeout, resetting connection
Jan 07 21:59:07 pi3 lastcast[6711]: WARNING:pychromecast.socket_client:Heartbeat timeout, resetting connection
Jan 07 21:59:07 pi3 lastcast[6711]: ERROR:pychromecast.socket_client:Failed to connect, retrying in 5.0s
Jan 07 21:59:07 pi3 lastcast[6711]: ERROR:pychromecast.socket_client:Failed to connect, retrying in 5.0s
Jan 07 21:59:07 pi3 lastcast[6711]: ERROR:pychromecast.socket_client:Failed to connect, retrying in 5.0s

I am listening to Spotify on my GH and nothing is being scrobbled at the moment.

Also for some reason, after doing an apt-get update, systemctl will not start lastcast service at startup. i am not sure where to find a log entry. I have to manually log in every time and restart it

**Comment by thecivvie** [comment]
I put a @reboot into my crontab which appears to have got around the startup issue

**Comment by erik** [comment]
No worries on the delay, thanks for the update 🙂

So this looks like different behavior from the original you had posted if I understand correctly. No unhandled error, but an unexplained pause where scrobbling doesn't work.

That heartbeat timeout message by itself is fine (and I'll see it in my logs as well), but if you were listening to music throughout the time period of the logs you posted, that's very weird. I haven't seen that happen yet.

Does lastcast scrobble correctly on startup and then exhibit this behavior, or does it just not scrobble at all?

Also, `retrying in 5.0s` makes me think that you're not on the most recent revision of lastcast, since in one of the more recent updates I changed the retry wait time to 0.01 seconds. Could you confirm the version you're running?

`pip show lastcast`

And just for the sake of completeness, let's check the dependency versions as well, in case it's a weird install issue:

`pip freeze | egrep -i 'cast|protobuf|zeroconf'`

**Comment by erik** [comment]
Any more information on this? I've released several versions of lastcast in the past few months, so knowing whether this issue is still valid would be helpful 😀

**Comment by thecivvie** [comment]
Sorry been meaning to ask you to close this. All is good in the land of thecivvie and lastcast

**Comment by erik** [comment]
Glad to hear it! Thanks for the update!
