### ISSUE TITLE
"None - None [None]" is scrobbled after resuming a track from pause

### ISSUE THREAD

**Issue by ghost** [erik/lastcast#35]
$ /usr/bin/lastcast --config /home/christopher/.lastcast.toml
Using chromecast: Christophers Google Home
Scrobbling: POLIÇA - Very Cruel [Shulamith]
**\# at this point playback is paused for more than 5 seconds and then resumed**
Scrobbling: None - None [None]
**\# a few seconds of running playback passed**
Scrobbling: POLIÇA - Very Cruel [Shulamith] **\# song is falsely scrobbled again**

**Comment by erik** [comment]
Interesting, I'm not able to reproduce this right away. I tried on a Google Home and a Chromecast, letting a song scrobble, pausing for 5+ seconds, and then resuming. Haven't seen `None - None [None]` or the double scrobble behavior. Does it happen consistently, or randomly? 

Also, could let me know which music player, version of Python, and OS you're using?

Thanks for reporting!

**Comment by erik** [comment]
My assumption is that this commit is somehow to blame: https://github.com/erik/lastcast/commit/20c03205012937915d9120deab4faa61b8703a66

But it's odd, since that code shouldn't be triggered unless something is currently playing.

**Comment by ghost** [comment]
It started happening after I updated to the latest version yesterday and now after I fully un- and reinstalled it does not happen anymore.
I don't know what could have caused this.
Anyway thanks for your help and your work! :)

Music player: Spotify
Python version: 3.6
OS: Arch Linux ARM

**Comment by erik** [comment]
That's the same setup I was using to test... very weird.

Please let me know if you see the issue pop up again! I'll try again later as well but if neither of us are able to reproduce after a while I'll assume the issue was some strange transient install issue.

**Comment by erik** [comment]
Hi @christopherpfisterde, any luck reproducing the issue? I haven't seen it happen locally yet.

**Comment by ghost** [comment]
Just checked my listening history; no further "none" scrobbles happened. It was probably really something else that caused it. Thanks for your help. :)

**Comment by erik** [comment]
Glad to hear it! 🙂
