### ISSUE TITLE
python 3.5 error

### ISSUE THREAD

**Issue by carmenchui** [erik/lastcast#40]
Hi Erik,

Great work with lastcast!  I installed the latest version of lastcast on a fresh install on my RaspberryPi and noticed the following:

> pi@raspberrypi:~ $ sudo systemctl status lastcast.service
> ● lastcast.service - Lastcast Server
>    Loaded: loaded (/etc/systemd/system/lastcast.service; disabled; vendor preset: enabled)
>    Active: active (running) since Sat 2018-03-17 11:38:24 EDT; 7min ago
>  Main PID: 14162 (lastcast)
>    CGroup: /system.slice/lastcast.service
>            └─14162 /usr/bin/python3 /usr/local/bin/lastcast
> 
> Mar 17 11:42:46 raspberrypi lastcast[14162]:   File "/usr/local/lib/python3.5/dist-packages/pylast/__
> Mar 17 11:42:46 raspberrypi lastcast[14162]:     "stream_id": stream_id, "context": context, "mbid": 
> Mar 17 11:42:46 raspberrypi lastcast[14162]:   File "/usr/local/lib/python3.5/dist-packages/pylast/__
> Mar 17 11:42:46 raspberrypi lastcast[14162]:     _Request(self, "track.scrobble", params).execute()
> Mar 17 11:42:46 raspberrypi lastcast[14162]:   File "/usr/local/lib/python3.5/dist-packages/pylast/__
> Mar 17 11:42:46 raspberrypi lastcast[14162]:     response = self._download_response()
> Mar 17 11:42:46 raspberrypi lastcast[14162]:   File "/usr/local/lib/python3.5/dist-packages/pylast/__
> Mar 17 11:42:46 raspberrypi lastcast[14162]:     raise NetworkError(self.network, e)
> Mar 17 11:42:46 raspberrypi lastcast[14162]: pylast.NetworkError: NetworkError: [Errno 110] Connectio
> Mar 17 11:44:38 raspberrypi lastcast[14162]: Scrobbling: Lillix - Poor Little Girl [Inside The Hollow
> lines 1-17/17 (END)

It seems to be returning Python errors.  Not sure if it's my installation but I have Python 3.5.3 installed currently.  Is there a different version of Python 3.5 I should be on?

**Comment by erik** [comment]
Hi @carmenchui, thanks for reporting!

So looking through the pylast code a bit, it seems like `errno 110 (Connection Timeout)` would point to an issue with the network you're trying to scrobble to, meaning either Last.fm or LibreFM were down / unreliable at the time.

I've personally noticed a lot of issues with API uptime trying to scrobble to LibreFM unfortunately.

It seems like it recovered about 2 minutes later and was able to scrobble again without actually crashing? The stack trace is pretty verbose, but as far as I can tell there's no problem with lastcast or your installation here. Perhaps I should move this info to a debug level log.

**Comment by carmenchui** [comment]
Hi @erik, thanks for the quick reply! Good to know nothing's wrong with my setup (lastcast 1.0.0 with Raspbian Stretch Lite); I'm only scrobbling to Last.fm, so it might have been a momentary glitch with Last.fm when it happened.

Since nothing's wrong, I'll go ahead and close this.
