### ISSUE TITLE
Scrobble information repeating

### ISSUE THREAD

**Issue by jakeledoux** [erik/lastcast#43]
Yesterday while listening to music, Lastcast replaced one in every few songs with "Hundaes - All Love" and eventually every song scrobbled was scrobbled with that information instead of the actual info. 

Restarting Lastcast seems to have temporarily fixed the issue.

**Comment by erik** [comment]
Oh wow, that's incredibly strange, I've never seen that myself.

Could you share some more details about what the cast device you're using is, as well as which music player you're using? Did this happen once or is it a recurring thing?

Thanks for reporting!

**Comment by jakeledoux** [comment]
Strange indeed!

Culprit is the Chromecast Gen 2 (not the ultra) playing a Spotify playlist. It's only happened once, and Lastcast had been running for about 6 days at that point.

Is there any sort of log that Lastcast creates that would be helpful to you? If it happens again I'll screencap the console and leave the scrobbles up on Last.fm for you to check out.

**Comment by erik** [comment]
If you run lastcast with `--verbose`, it'll spit out some more info when something errors. Could you do that just in case it happens again?

By itself, lastcast will only print to stderr, but if you run it with the systemd setup, for example, you can use `journalctl` to view the logs. For me, I run `journalctl -uf lastcast` in a separate window to watch the logs as they're generated.

**Comment by jakeledoux** [comment]
You're pretty speedy with these responses!

I'll give that a go. Forgot to mention earlier that Lastcast is running on Windows 10, if that makes any difference.

**Comment by erik** [comment]
If I don't respond quickly I'll completely forget to altogether 😄 

Ah, so I've never tested lastcast on Windows, it could be possible that there are some platform specific bugs, but I doubt it, since most of the heavy lifting is done by other libraries. 

But yeah, let me know if you see it come up again, and in the mean time I'll try to reproduce the issue myself

**Comment by jakeledoux** [comment]
Still no recurrence of the issue, which is kind of disappointing. I was hoping we could get to the bottom of this.

**Comment by erik** [comment]
Hmm, maybe the chromecast itself got into a weird state?

Either way, thanks for updating! I'll keep the ticket open for now.

**Comment by erik** [comment]
Hey @NyanJaik! Going to close out this ticket for now, but feel free to open it back up if you've noticed anything buggy.

**Comment by jakeledoux** [comment]
No issues since! Last.fm was going through some weird changes then so it was probably on their end.
Cheers.
