### ISSUE TITLE
Dedicated system required?

### ISSUE THREAD

**Issue by phunni** [erik/lastcast#46]
Apologies for using the "issues" to simply ask a question! I want to use lastcast to scrobble what my new home mini plays and everything I read suggests running it on a raspberry pi.  As it happens, I do have a spare one of those sitting around, but I also have a media server that I use which is running Arch Linux and I wondered if there was any reason I shouldn't simply set up lastcast on that as a systemd service? Does it need a system that's completely dedicated to it?

**Comment by erik** [comment]
Nah you won't need a dedicated server for lastcast, it's not very resource intensive at all. The media server should work well for this. The only reason the raspberry pi was mentioned was that it was my original setup, and for someone without a home server, it's a better choice than running on a laptop or something.

Thanks for asking! I'll make the documentation more clear on this.

**Comment by erik** [comment]
Closing this out for now, please let me know if you have more questions!
