### ISSUE TITLE
Youtube Music Missing artist information

### ISSUE THREAD

**Issue by comicmuse** [erik/lastcast#47]
Casting Youtube Music from my phone to Chromecast.
Lastcast scrobbles just the song name, with "None" as the artist name. 

I've noticed that the Chromecast notification on my phone only has the artist information also. Suspect this could be related? Anyone else seen this? 

```
Nov 28 17:15:20 raspberrypi lastcast[591]: Scrobbling: None - Halo [None]
Nov 28 17:19:42 raspberrypi lastcast[591]: Scrobbling: None - Somewhere Only We Know [None]
Nov 28 17:23:28 raspberrypi lastcast[591]: Scrobbling: None - Apologize [None]
Nov 28 17:27:20 raspberrypi lastcast[591]: Scrobbling: None - Fix You [None]
```

**Comment by erik** [comment]
Thanks for reporting!

Does this affect all music you've tried to scrobble, or only certain songs? If it's only certain tracks, could you share some links so I can try to reproduce this myself?

**Comment by comicmuse** [comment]
I only just tried it this evening, and it affected those four in a row - it was just a playlist - Easy 00s, or something. I'll test it again later and see if I can find anything more out.

**Comment by erik** [comment]
Hi @comicmuse, just tried locally and I wasn't able to reproduce the issue.

I was able to see artists and albums when going through the "Easy 00s" playlist.

Could you share some more details about your setup? Some stuff like: 
- lastcast version
- ios / android
- cast device

**Comment by comicmuse** [comment]
Sorry for not coming back earlier. I can't replicate either any more. It did happen to me for a whole evening. 

It must have been a temporary youtube issue. I'll keep an eye on it and re-open if I see it again, but I don't think there's anything more to do here for now.

**Comment by erik** [comment]
Ahh, got it. Thank you for the update!
