### ISSUE TITLE
Is it possible to make it work on Android?

### ISSUE THREAD

**Issue by 7merlin** [erik/lastcast#48]

**Comment by erik** [comment]
Hi @7merlin!

Theoretically you could use something like [python-for-android](https://python-for-android.readthedocs.io/en/latest/) to package up lastcast for use with Android, but I've never gone down this route so I don't have any idea how feasible it is.

Realistically though, there should be other scrobblers you can use that are meant for your phone. lastcast is more or less intended to be running on an always-on machine.

Maybe try something like this instead? https://github.com/tgwizard/sls

**Comment by erik** [comment]
Closing this issue out for now, please feel free to reopen this (or another) if you have more questions about lastcast!

**Comment by 7merlin** [comment]
Hi Erik,

I have a bunch of always-on Android devices in my house (Android TV boxes). None always-on Mac/Windows/Linux machines. Having my Mac laptop running all the time for this is annoying. But hey, I'm not complaining. At least there is a way to scrobble whatever I listen on my Google Homes around the house. Thanks for your work!

Maybe I could make this work on my Synology NAS. It's supposed to support python.
