### ISSUE TITLE
Exception in thread zeroconf-Engine

### ISSUE THREAD

**Issue by joeysapp** [erik/lastcast#5]
Hey, so I'd love to use this - I'm getting this error after configuring everything and running in terminal. I've tried most solutions I can think of and I'm stuck. I'm running macOS 10.11.4 on an early 2015 MBP retina. After getting the error, it seems to continue running but whatever is playing on my Spotify doesn't play on my chromecast or scrobble. Thanks for this project!!

```
zs-MacBook-Pro:~ zoo$ lastcast
Exception in thread zeroconf-Engine:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/site-packages/zeroconf.py", line 946, in run
    rr, wr, er = select.select(rs, [], [], self.timeout)
error: (9, 'Bad file descriptor')

Using chromecast:  DeviceStatus(friendly_name=u'foo', model_name=u'Chromecast', manufacturer=u'Google Inc.', api_version=(1, 0), uuid=UUID('foo'), cast_type='cast')
```

After some research I see this: https://github.com/jstasiak/python-zeroconf/pull/88 and it looks like this is the issue. This is resolved by editing zeroconf.py accordingly.

Just curious, I assume you still have to start the casting to chromecast with iOS/Android mobile Spotify apps, but then can use lastcast and change the music on your computer?

**Comment by erik** [comment]
Thanks for digging into the issue, I've run into it as well and it's definitely annoying, but at least lastcast continues running. If I'm reading the threads right, looks like we're waiting on python-zeroconf and pychromecast to merge some PRs to fix? I can update to a new library version when that happens.

> Just curious, I assume you still have to start the casting to chromecast with iOS/Android mobile Spotify apps, but then can use lastcast and change the music on your computer?

Yep, you need to initiate the casting from iOS/Android, but you should be able to use your desktop spotify client (and media keys etc) to control the music on the Chromecast. Lastcast only deals with scrobbling to last.fm, so it shouldn't affect anything about actually controlling music playback.

**Comment by joeysapp** [comment]
Yeah - I just went in and edited my zeroconf.py to the content in #88 and it all works. Just two lines, so I assume once they merge it should be fine. 

Sounds good, all works and I've got your bash script running. Thanks!

**Comment by erik** [comment]
Awesome, glad to hear it!

I'll set myself a reminder to check back on those PRs and update when they get merged.
