### ISSUE TITLE
Docker image?

### ISSUE THREAD

**Issue by jack-fin** [erik/lastcast#50]
Hello!

I was curious if you would be interested in providing a docker image for lastcast? I really like this software and a Docker image would make it very easy to deploy on a NAS. 

I have created a fork of this repository to setup a Docker file. It all works, except the application cannot find Google devices on the network. This may be due to needing certain ports open?

My fork with the Docker file and dirst attempt at readme is: https://github.com/jack-fin/lastcast

**Comment by erik** [comment]
Definitely interested in including the Dockerfile once we get it working, thanks for getting the ball rolling there!

Did some quick searching, and I found some similar issues on the home-assistant project, which is using the same Chromecast library as lastcast:

- home-assistant/home-assistant#13239: cast groups do not show up in docker without net=host

Could that be relevant to your issue?

**Comment by danopia** [comment]
The Chromecast discovery technology can't pass through network bridges. Docker defaults to using a bridge network for your containers. You'll have to add `--net=host` for any software like lastcast that needs to discover other devices on your network. So try that out and see if it fixes your issue.

I believe that home-assistant works a bit differently, and accepts a list of Chromecast IP addresses in the configuration. So it doesn't need to discover the devices, and can operate without docker's host-networking mode.

**Comment by jack-fin** [comment]
Thanks danopia, that indeed was the problem. If I deploy this Docker image using the "host" option for net the application works as expected. I have updated my Readme to say to deploy with this option.

**Comment by erik** [comment]
Thanks again @jack-fin!

This is now available at `rkprc/lastcast` (I couldn't get the `erik` username 😢)
