### ISSUE TITLE
Wizard not completing

### ISSUE THREAD

**Issue by jbmfg** [erik/lastcast#53]
As I run the wizard it just hangs after i put in my last.fm creds.  I had this working a while back and grabbed my old toml config and used it.  When i start last cast it just hangs.  Not sure what other info i can provide so let me know if there are logs i can send

**Comment by erik** [comment]
If you could rerun the command with the `--verbose` CLI flag, that may help to uncover the issue. 

My guess is that for some reason, detecting the Chromecast devices on your network isn't working, and it's getting stuck there. If you're using Docker, make sure you're passing the `--net=host` flag to `docker run`.

**Comment by jbmfg** [comment]
Thanks erik.  The verbose flag doesnt help, still just hangs at the same places.  Not docker but am running on a lxd container.  I bet it's something to do with that causing it to not run.  I'm not sure where to look to figure it out

**Comment by erik** [comment]
Hmm, yeah, sounds like that would end up being the culprit.

I've never interacted with LXD containers directly, so I can't really help too much with debugging, but I did find [this forum discussion](https://discuss.linuxcontainers.org/t/equivalent-of-docker-net-host-in-lxd-container/4426), which may be a good starting point?

Please keep me updated if you find a solution so that I can update the documentation!

**Comment by jbmfg** [comment]
I am able to ping the google home from the LXD container.  I wonder if it would be possible to just specify the ip address of the google home in the lastcast config rather than detecting the devices?

**Comment by erik** [comment]
That makes sense if there's an issue with multicast IPs inside the container. 

Looks like pychromecast [would support](https://github.com/balloob/pychromecast/blob/master/pychromecast/__init__.py#L176) passing in an IP address/host directly. I'd be open to including this as a config option if you're able to help test out this change.

**Comment by jbmfg** [comment]
Yup, happy to help!  Just let me know when you have a chance to include this

**Comment by erik** [comment]
Included your PyChromecast version bump to fix this in version 2.0.0. Thanks again!
