### ISSUE TITLE
Support for windows?

### ISSUE THREAD

**Issue by facundopignanelli** [erik/lastcast#55]
I have an always-on windows machine that runs as a Plex server. Would love to use this, but I'm not sure how to do so on Windows.

If that's already possible and it's just a case that I'm not realizing it, I apologize.

**Comment by erik** [comment]
Hey @facundopignanelli, lastcast should work on Windows as-is unless something changed recently in one of the libraries I'm using. I unfortunately don't have a Windows machine I can use to confirm this though. 

As long as you have Python3, you should be able to install it with `pip` directly. Alternatively you could run it inside Docker using the README instructions

**Comment by facundopignanelli** [comment]
Oh, thanks for the fast reply! I will get python for windows (and once I figure it out how to use it) I will let you know if it works. Thank you!

**Comment by facundopignanelli** [comment]
Hi! I managed to install phyton and by using the command prompt on windows I could get lastcast installed by the command
 `pip3 install lastcast` 
Then I'm trying to use the command
 `py lastcast --wizard`
 to start the wizard but I'm getting the following error:
 `C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1729.0_x64__qbz5n2kfra8p0\python.exe: can't find '__main__' module in 'lastcast'`,

Any help would be greatly appreciated!

**Comment by erik** [comment]
Try `py lastcast.__init__ --wizard` (or possibly `py -m lastcast.__init__ --wizard`, not sure how the Windows CLI works)

If that doesn't work I think the fix would be simply to create a simple `__main__.py` next to `__init__.py` which calls the existing `main()` function

**Comment by erik** [comment]
Hey @facundopignanelli, I just pushed a new version of lastcast which should work the way you were calling it before. Give it a try and see if it solves your issue.

```
pip3 install lastcast==2.0.1
py lastcast --wizard
```
