### ISSUE TITLE
Duration field is None type when polled between songs

### ISSUE THREAD

**Issue by ravishchawla** [erik/lastcast#6]
I saw this a few times. The duration field in the MediaStatus object is of Nonetype when the chromecast is polled between songs. It crashes on line 85

`        if status.current_time > SCROBBLE_THRESHOLD_SECS or \
           (status.current_time / status.duration) >= SCROBBLE_THRESHOLD_PCT:
            self._scrobble(meta)`

It just requires a check before this statement for data types of all fields in the object.

**Comment by erik** [comment]
Nice catch, I'll add a quick fix later today

**Comment by erik** [comment]
@ravishchawla could you give the change in #7 a shot to see if it fixes the issue for you?

**Comment by ravishchawla** [comment]
Yes, it's scrobbling with no problems now. Thanks for the quick fix!

**Comment by erik** [comment]
Awesome, thanks for reporting the issue
