### ISSUE TITLE
Add Homebrew package formula

### ISSUE THREAD

**Issue by korthout** [erik/lastcast#9]
Many macOS users like to use Homebrew as there main package manager and so do I. I'd love to see a Homebrew package formula for this. 

See [https://github.com/Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core)

**Comment by erik** [comment]
Definitely a nice to have. I'll look into this around the time of the next pip release

**Comment by korthout** [comment]
Oops, that (close and reopen) was not supposed to happen. I'm happy you like the idea. I don't think I have time to take this on anytime soon (I'm graduating soon), although I'm very much interested in helping out. Perhaps after my graduation.

**Comment by erik** [comment]
Quick update since it's almost been a year since this ticket was first opened (where does the time go?).

I haven't done anything yet to get a homebrew package merged mostly due to this line from the FAQ:

> We frown on authors submitting their own work unless it is very popular.
> https://docs.brew.sh/Acceptable-Formulae.html

I don't think lastcast quite qualifies as "very popular"

**Comment by erik** [comment]
Closing this out for now since it's an older ticket at this point.
